version: "3"

services:

  tracing-service:
    build:
      context: .
    image: tracing-service:1.0.1
    ports:
    - "8080:8080"
    networks:
    - jee8net

  jaegertracing:
    image: jaegertracing/all-in-one:1.7.0
    ports:
    - 6831:6831/udp
    - 16686:16686
    networks:
    - jee8net

networks:
  jee8net:
    driver: bridge
